### ISSUE TITLE
Expose Mona Lisa features on github pages by using webassembly 

### ISSUE THREAD

**Issue by 4383** [nathan-hoche/MonaLisa#8]
Hi Nathan,

Is exposing Mona Lisa online through [github pages](https://pages.github.com/) and [webassembly](https://webassembly.org/) is something that could interest you?

That architecture could rely on [Wasmer](https://github.com/wasmerio/wasmer).

Wasmer could help to expose Mona Lisa online to your user through static web page and without requiring any backend server.

Let me know your thoughts.

**Comment by nathan-hoche** [comment]
Hi, sorry for the late response!

I appreciate your proposal, but I’m not sure how useful it would be. Since the program requires several hours to produce good results, I think it’s better to run it locally.

Running it locally prevents the risk of losing progress due to a reload, a browser crash, or a computer shutdown. It also allows for continuous checkpoint saving. These checkpoints cis a need to resume or continue progress from a specific point.

**Comment by 4383** [comment]
No problem.
You are right. I missed to consider the duration. 
Thanks for your feedback.
